### ISSUE TITLE
Any authenticated user can add/mod/del records in any zone

### ISSUE THREAD

**Issue by iavael** [allegro/django-powerdns-dnssec#174]
in powerdns/models/powerdns.py permissions to work with record are granted to every authenticated user

``` python
rules.add_perm('powerdns.add_record', rules.is_authenticated)
rules.add_perm('powerdns.change_record', rules.is_authenticated)
rules.add_perm('powerdns.delete_record', rules.is_authenticated)
```

settings_local.py (just in case)

``` python
import ldap
from django_auth_ldap.config import LDAPSearch

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'powerdns',
        'USER': 'powerdns',
        'PASSWORD': 'powerdns',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

AUTHENTICATION_BACKENDS = (
    'rules.permissions.ObjectPermissionBackend',
    'django.contrib.auth.backends.ModelBackend',
    'django_auth_ldap.backend.LDAPBackend',
)

AUTH_LDAP_SERVER_URI = "ldap://ldap.example.com"

AUTH_LDAP_AUTHORIZE_ALL_USERS = True
AUTH_LDAP_BIND_DN = "cn=reader,dc=example,dc=com"
AUTH_LDAP_BIND_PASSWORD = "VERYSECRET"
AUTH_LDAP_USER_SEARCH = LDAPSearch("ou=users,dc=example,dc=com",
    ldap.SCOPE_SUBTREE, "(&(uid=%(user)s)(objectClass=posixAccount))")

AUTH_LDAP_CONNECTION_OPTIONS = {
        ldap.OPT_DEBUG_LEVEL: 0,
        ldap.OPT_REFERRALS: 0,
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'stream_to_console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler'
        },
    },
    'loggers': {
        'django_auth_ldap': {
            'handlers': ['stream_to_console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    }
}
```

**Comment by mkurek** [comment]
Yes - we're dropping support for such permissions right now. 

Historical context: first, we've developed dnsaas as a wrapped around django admin (with couple of features, like permissions, requests for changes etc). Then we've decided that it's too complicated to maintain and too confusing for the user, so we've created new api (v2) and build gui in angular on top of it. Every change should "enter" through this api - we've left the admin interface only for "real" superuser (admin of DNS system).

Right now, we're supporting per-record permissions (each record has assigned owner) and we're at the end of developing permissions based on service (each record will have assigned service, each service will have owners and they will be able to change record directly, otherwise the change should be accepted (we're using Jira for this)).

@iavael - do you expect any particular behaviour from permissions in dnsaas?

**Comment by iavael** [comment]
I expected that operations on records would be controlled by permissions on zones, otherwise requests are created.
Couple of weeks ago I saw this behaviour in master if I removed user from staff group in LDAP, when he was logged in. Then his session kept and permissions worked as expected in previous paragraph.

**Comment by mkurek** [comment]
> I expected that operations on records would be controlled by permissions on zones, otherwise requests are created.

Right now we're working on permissions based on services (each service will have assigned owner(s) and he will be able to do operation on record without requesting for permission). We'll drop "direct" owner of record soon after these permissions will be implemented.

> Couple of weeks ago I saw this behaviour in master

Are you sure? I don't remember such behaviour in our dnsaas :smile:

> I removed user from staff group in LDAP, when he was logged in. Then his session kept ..

Yes - groups are "refreshed" only during login

**Comment by mzdeb** [comment]
Sorry, this project is not maintained anymore.
